world: "world"
dimension: "minecraft:lobby"
name: "lobby"
sorting: 10
start-pos: { x: 0, z: 0 }
sky-color: "#7dabff"
void-color: "#000000"
sky-light: 1
ambient-light: 0.15
remove-caves-below-y: 55
storage: "file"
enable-perspective-view: true
enable-flat-view: true
enable-free-flight-view: true
enable-hires: true
ignore-missing-light-data: true
marker-sets: {}
